site_name: Mkdocs
repo_url: https://github.com/SYathesh/Mkdocs
theme:
  custom_dir: custom_templates
  font: 
    text: Roboto
    code: Roboto Mono
  name: 'mkdocs'
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
    - projects
    - optimize
    - offline
  language: en
  palette:
  - scheme: slate
    primary: light blue
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - scheme: default
    primary: blue
    accent: deep orange
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
nav:
  - Version 1.0: .\RoboCall\Robo_Call.md
  - Version 1.1: .\Store_&_Call_Center_CRM\Advaita.md
  - Version 2.0: .\docs\FAQ.md
  
extra:
  hide: 
    - footer
  copyright: Copyright &copy; 2024 - 2042 S Yathesh
  
  social: 
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SYathesh
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/SYathesh
    - icon: fontawesome/brands/pied-piper-alt
      link: https://github.com/SYathesh



 
 

